# Task 1 & Task 2: Messages & Message Placeholders
# Student: Parth Dadhaniya

from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from config import get_chat_model


def task1_conceptual_answers():
    print("--- Task 1: Understanding Chat Messages ---")
    print("""
1. What are SystemMessage, HumanMessage, and AIMessage?
   - SystemMessage: Sets the behavior, tone, and rules for the chatbot.
   - HumanMessage: The message sent by the user.
   - AIMessage: The response generated by the AI model.

2. Why message-based prompting is better than single prompts?
   - In single string prompts, everything is merged into one block of text,
     which makes it hard to distinguish instructions from user input.
   - Message-based prompting clearly separates roles (system, human, AI).
   - It makes it very easy to append past conversation turns dynamically.
""")


def task2_messages_placeholder():
    print("--- Task 2: MessagesPlaceholder Usage ---")

    # 1. Initialize model
    model = get_chat_model()

    # 2. Build prompt template with MessagesPlaceholder for chat history
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a friendly customer support assistant."),
        MessagesPlaceholder(variable_name="chat_history"),
        ("human", "{user_input}")
    ])

    chain = prompt | model
    chat_history = []

    # Test conversation turns
    turns = [
        "Hi, my name is Parth.",
        "What is my name?",
        "Explain Python lists in simple words."
    ]

    for turn_num, user_msg in enumerate(turns, start=1):
        print(f"\nTurn {turn_num}:")
        print(f"User: {user_msg}")

        # Call chain with current history and input
        response = chain.invoke({
            "chat_history": chat_history,
            "user_input": user_msg
        })
        ai_reply = response.content
        print(f"AI  : {ai_reply}")

        # Update chat history
        chat_history.append(HumanMessage(content=user_msg))
        chat_history.append(AIMessage(content=ai_reply))

    print(f"\nTotal messages stored in history: {len(chat_history)}")


if __name__ == "__main__":
    task1_conceptual_answers()
    task2_messages_placeholder()
